server:
  port: 8086

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # fine for springdoc on SB 2.7

  # --- DataSource (Hikari by default) ---
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:creche}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  sql:
    init:
      mode: never

  # --- Mail (real Gmail SMTP settings) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: manymenfa@gmail.com
    password: igae egab tzxb fdva
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.mail: INFO
