server:
  port: 8086

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=creche
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: manymenfa@gmail.com
    password: igae egab tzxb fdva
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.mail: INFO
