name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # runs when you push to main
  pull_request:
    branches: [ "main" ]   # runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Set up JDK (update version if needed)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4. Build & Test
      - name: Build with Maven
        run: mvn clean install -B

      # 5. Run Unit Tests
      - name: Run tests
        run: mvn test

      # 6. Package JAR
      - name: Package application
        run: mvn package -DskipTests

      # 7. Upload JAR as artifact (downloadable from GitHub)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: creche-server-jar
          path: target/*.jar
